# Generated by Django 4.1.4 on 2023-02-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='imagem',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to=''),
        ),
    ]
