# Generated by Django 4.1.4 on 2023-02-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_remove_perfil_id_alter_perfil_foto_alter_perfil_user'),
        ('blog', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.perfil'),
        ),
    ]
