# Generated by Django 4.1.4 on 2023-01-05 01:46

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_conteudo_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_capa',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog/img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
