# Generated by Django 4.1.4 on 2023-02-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_remove_perfil_id_alter_perfil_foto_alter_perfil_user'),
        ('blog', '0003_comentario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.perfil'),
        ),
    ]
