# Generated by Django 4.1.4 on 2023-02-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_topico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='resumo',
        ),
    ]
